sonar.projectKey=PSergio984_ceit-ai-sidecar
sonar.organization=psergio984
sonar.projectName=CEIT AI Sidecar
sonar.python.version=3.13
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
